name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true

      - run: rye sync

      - name: format
        run: rye fmt --check

      - name: lint
        run: rye lint

      - name: Run tests
        run: rye run pytest -n auto

      - name: Run slow tests
        run: rye run pytest -m slow --slow -n auto
